# Generated by Django 4.2.11 on 2024-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_id', models.CharField(max_length=255)),
                ('max_tokens', models.IntegerField(default=8192, help_text='Global Setting')),
                ('stop_sequences', models.TextField(blank=True, help_text='Global Setting', null=True)),
                ('temperature', models.FloatField(default=0, help_text='Global Setting')),
            ],
        ),
    ]
