# Generated by Django 4.2.11 on 2024-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='region',
            field=models.TextField(blank=True, default='us-east-1', help_text='Global Setting', null=True),
        ),
    ]
