# Generated by Django 4.2.11 on 2024-04-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_settings', '0002_basemodel_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='region',
            field=models.TextField(default='us-east-1', help_text='Global Setting'),
        ),
    ]
