# Generated by Django 4.2.11 on 2024-04-17 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checker_name', models.CharField(max_length=255)),
                ('checker_description', models.TextField()),
                ('checker_prompt', models.TextField()),
                ('checker_time_limit', models.IntegerField()),
                ('max_tokens', models.IntegerField(default=8192)),
                ('stop_sequences', models.TextField(blank=True, null=True)),
                ('temperature', models.FloatField(default=0)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_settings.basemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CorePrompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_prompts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_description', models.TextField()),
                ('skill_examples', models.TextField(blank=True, null=True)),
                ('max_tokens', models.IntegerField(default=8192)),
                ('stop_sequences', models.TextField(blank=True, null=True)),
                ('temperature', models.FloatField(default=0)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_settings.basemodel')),
                ('skill_checkers', models.ManyToManyField(blank=True, null=True, related_name='skill_checkers', to='role_chatbot.checker')),
            ],
        ),
        migrations.CreateModel(
            name='RoleChatbot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('role_background', models.TextField()),
                ('chat_background', models.TextField()),
                ('language_styles', models.TextField()),
                ('skills', models.ManyToManyField(related_name='role_chat_bot_skills', to='role_chatbot.skill')),
                ('system_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_chat_bot_system_prompt', to='role_chatbot.coreprompt')),
            ],
        ),
    ]
