# Generated by Django 4.2.11 on 2024-04-17 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CorePrompt',
            new_name='SystemPrompt',
        ),
    ]
