# Generated by Django 4.2.11 on 2024-04-17 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system_prompt', models.TextField()),
                ('preset_user_message', models.TextField(blank=True, help_text='Only for the first round', null=True)),
                ('preset_assistant_message', models.TextField(blank=True, help_text='Only for the first round', null=True)),
                ('description', models.TextField(default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('max_tokens', models.IntegerField(default=8192)),
                ('stop_sequences', models.TextField(blank=True, null=True)),
                ('temperature', models.FloatField(default=0)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_prompt', to=settings.AUTH_USER_MODEL)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_settings.basemodel')),
            ],
        ),
    ]
