# Generated by Django 4.2.11 on 2024-04-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueChecker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dialogue_checker_name', models.CharField(max_length=100)),
                ('dialogue_checker_description', models.TextField()),
                ('dialogue_checker_prompt', models.TextField()),
                ('max_tokens', models.IntegerField(default=8192)),
                ('stop_sequences', models.TextField(blank=True, null=True)),
                ('temperature', models.FloatField(default=0)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_settings.basemodel')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheckChatbot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qc_chat_name', models.CharField(max_length=100)),
                ('qc_chat_background', models.TextField()),
                ('dialogue_checkers', models.ManyToManyField(related_name='quality_check_chatbots', to='quality_check_chatbot.dialoguechecker')),
            ],
        ),
    ]
