# Generated by Django 4.2.11 on 2024-04-18 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_settings', '0001_initial'),
        ('quality_check_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguechecker',
            name='is_knowledge_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualitycheckchatbot',
            name='dialogue_checkers',
            field=models.ManyToManyField(blank=True, null=True, related_name='quality_check_chatbots', to='quality_check_chatbot.dialoguechecker'),
        ),
        migrations.CreateModel(
            name='KnowledgeBaseDialogueChecker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('knowledge_base_dialogue_checker_name', models.CharField(max_length=100)),
                ('knowledge_base_dialogue_checker_description', models.TextField()),
                ('knowledge_base_dialogue_checker_prompt', models.TextField()),
                ('query_list_generation_prompt', models.TextField(help_text='query list generation prompt is used for generating key-words or key-sentences to retrieval related information in vector databse, please let it output a list.')),
                ('max_tokens', models.IntegerField(default=8192)),
                ('stop_sequences', models.TextField(blank=True, null=True)),
                ('temperature', models.FloatField(default=0)),
                ('knowledge_base_id', models.TextField(blank=True, help_text='Now, only support the bedrock knowledge base. Please make sure you can access the knowledge base in your environment.', null=True)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_settings.basemodel')),
            ],
        ),
        migrations.AddField(
            model_name='qualitycheckchatbot',
            name='knowledge_base_dialogue_checkers',
            field=models.ManyToManyField(blank=True, null=True, related_name='knowledge_base_quality_check_chatbots', to='quality_check_chatbot.knowledgebasedialoguechecker'),
        ),
    ]
