# Generated by Django 4.2.11 on 2024-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_check_chatbot', '0002_dialoguechecker_is_knowledge_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasedialoguechecker',
            name='knowledge_base_id',
            field=models.TextField(default='', help_text='Now, only support the bedrock knowledge base. Please make sure you can access the knowledge base in your environment.'),
        ),
    ]
